### ISSUE TITLE
本番環境で GitHub認証できない問題を解決

### ISSUE THREAD

**Issue by Saki-htr** [Saki-htr/fjord-choice#119]
## 問題
- GitHub認証機能が、開発環境では問題なく動くが、本番だとエラーになる
- エラーは同じ操作なのに2パターンあり、
1つ目は
![image](https://user-images.githubusercontent.com/58052292/189511271-4beb5bd2-a90a-42e2-94f0-7ca9cc7f31ba.png)
2つ目は「localhostに接続できません」(開発環境で`rails s`をしてない状態で接続すると出る、よく見るエラー)

**Comment by Saki-htr** [comment]
解決したので、closeします。

### 原因
-  GitHubにOAuth Appとしてfjord-choiceを登録したときに、開発環境だったのでパRailsの説明に則って、Authorization callback URLを、`http://localhost:3000/auth/github/callback`に登録していたため。
- なので、開発環境ではうまくいき、本番環境ではエラーになった。
- エラー2パターン出ていたが、よく見ると両者共にURLが `http://localhost:3000/auth/github/callback?error=redirect_uri_mismatch&error_description=The+redirect_uri+MUST+match+the+registered+callback+URL+for+this+application.&error_uri=https%3A%2F%2Fdocs.github.com%2Fapps%2Fmanaging-oauth-apps%2Ftroubleshooting-authorization-request-errors%2F%23redirect-uri-mismatch&state=e8e138572ee15bf485e8c85abdaecfbf2d6b77f161b2a977` のように、`localhost:3000`に接続してしまっていた。
- なので、GitHubのOAuth Appsの設定で、callbacl URLを`https://fjord-choice.herokuapp.com/auth/github/callback`に変更したら、問題なく動作した。

🤔 こうなると、本番環境では動くが、開発環境では GitHub認証機能ができなくなる。他の方はどうされているんだろう。

**Comment by haruguchi-yuma** [comment]
> 🤔 こうなると、本番環境では動くが、開発環境では GitHub認証機能ができなくなる。他の方はどうされているんだろう。

開発環境とは別に本番環境用のGitHubアプリケーションの登録をするのが普通なのかなと思います。
パRailsで言うとp.292で言及されています:muscle:

**Comment by Saki-htr** [comment]
@haruguchi-yuma さん
教えてくださってありがとうございます🙏✨

仰る通り、パRailsを見たら、
> 別の環境で動かしたい場合には再度GitHubアプリケーションを登録する

とありました。私も本番環境用に追加で登録します!

**Comment by haruguchi-yuma** [comment]
頑張ってくださいー！！ 🚀
