### ISSUE TITLE
URL設計

### ISSUE THREAD

**Issue by Saki-htr** [Saki-htr/fjord-choice#12]
[リソース・DB設計 \| FJORD BOOT CAMP（フィヨルドブートキャンプ）](https://bootcamp.fjord.jp/practices/229)

## ポイント付け会メモ
- 登録時や退会時にも何らかの HTTP 通信が発生する
- ユーザー登録(POST)とユーザー削除(DELETE)をするためのURL(`/sessions`など)が必要
- パRailsのルーティングの説明が分かりやすい
- 参考
  - [Design URI · Issue \#16 · eatplaynap/shadone](https://github.com/eatplaynap/shadone/issues/16)

**Comment by Saki-htr** [comment]
## 提出1回目

|method | path | description
|-- | -- | --
|GET | / | 開発メンバーの状況が分かる一覧画面

### 説明
- 現在、「開発メンバーの状況が分かる一覧画面」のページのみを作成しようと考えています。そのため、URLは`/`一つとしました。
- サービスの右上の「利用規約に同意して、メンバーに自分を追加する」ボタンをクリックした時に、GitHubの認証画面がでますが、こちらは私のアプリではなくGitHubが用意しているページになりますので、除外しています。

**Comment by Saki-htr** [comment]
## ポイント付け会メモ
- パRailsのルーティングを見ると良い
- ユーザー登録(POST)とユーザー削除(DELETE)をするためのURL(`/sessions`など)が必要

**Comment by kfukai23** [comment]
OK です！:+1:

**Comment by Saki-htr** [comment]
OKをいただいたので、closeいたします。
