### ISSUE TITLE
DB設計

### ISSUE THREAD

**Issue by Saki-htr** [Saki-htr/fjord-choice#38]
### タスク
- [x] DB設計にPR一覧のurlカラムを追加するか検討する (もしかしたらDBに保存する必要ないかも。URLにDBのuserのnameを埋め込めば作れそう) →`name`カラムさえあればURLは生成できるので、URLをDBに保存する必要はないと判断した。
- [x] レビューのお返しで、中間テーブルの名前について質問する

### 参考
- [リソース・DB設計 \| FJORD BOOT CAMP（フィヨルドブートキャンプ）](https://bootcamp.fjord.jp/practices/229)

### ポイント付け会でいただいたアドバイス
- 論理設計と物理設計に分けてやったほうが良いかも
  - 論理設計と物理設計とは：https://discord.com/channels/715806612824260640/825963978361798676/836859215011512410 
- [Design DB · Issue \#7 · eatplaynap/shadone](https://github.com/eatplaynap/shadone/issues/7)のように、実際にマイグレーションファイルを作る時も合わせて提出すると、カラムのデータ型とインデックスも考えることになるので良さそう

**Comment by Saki-htr** [comment]
## 7/16(土) メンターさんペアプロメモ

### 必要なテーブルは7つ

<img width="646" alt="image" src="https://user-images.githubusercontent.com/58052292/179345608-7147613f-6047-4a65-a7da-52f61d111786.png">

### データの流れ 
- PRの生JSONデータを元に & issueの生JSONデータを元に、表形式のDBへデータを落としこんでいく
1. 最初に、生JSONから必要なDBを抜き出して、表形式のDBにデータを入れていく
2. usersテーブル(私のアプリにサインアップしたユーザー)を作成
3. どのユーザーに、どのissueが紐づいているかのテーブルを作成する &  どのユーザーに、どのPRが紐づいているかのテーブルを作成する
- 1~3まで、バックグラウンドジョブでやる必要がある。
- **データベースは変えにくい部分なので、設計はつまづくと大変。しっかりと行う。**

### 全体のテーブルの構成が、前回ペアプロさせていただいた時に仰っていたのと違う理由
- #34 のDB保存イメージと変わった理由
- 1つのPRに、レビュワーが同時に2人(受講生とkomagataさん)登録される可能性がある。
  - 現状、「任意の受講生1名をレビュワー登録してお願いし、**Approveされたら**komagataさんをレビュワーとして登録してお願いする」というルールだが、2名同時に登録される可能性もあるため。
- 1つのPRにレビュワーが2人登録された場合、以下のテーブル設計ではまずい。
![image](https://user-images.githubusercontent.com/58052292/179346022-607fce92-2b18-4d5e-a95a-be97d5bf780c.png)

### データの保存の検証よりも、まずデータモデリングをした方が良い
- データモデリングとは：現実世界のものをデータに落とし込む作業。(例)ECサイト：どんな商品があるか、サイズはどんなものがあるか、カラーは何色があるか等。
- 具体的には、
  - **そもそもどういうデータがあるかを洗い出すために、スプレッドシートに表を作って実際のデータを入れて、どんな値が入るか考える**
  - **そのデータは、いつどこで生まれる&消えるのかを考える**
 - この2つを考えることで、テーブル同士のリレーションシップが分かる。

### データは、いつどこで生まれる&消えるのか(補足)

<img width="596" alt="image" src="https://user-images.githubusercontent.com/58052292/179346594-b8900f9f-628e-4003-8306-97d1d1401fb7.png">

#### 例1:チャットアプリ
  - 前提：usersテーブルとmessagesテーブルがある
  - userのデータは、そのアプリに登録(sign up)した時に作られる
  - messageのデータは、userがmessageを送った(post)時に作られる
  - user
    - 1回もメッセージを送らない人もいることが考えられる 
    - メッセージは1回でも複数回でも、何回でも送れる
  - message
    - 1つのメッセージには、そのメッセージを送ったユーザーが必ず1名存在している
    - 1つのメッセージに複数名紐づいていることはあり得ない(複数人が1つのメッセージを送信はあり得ない)
  - よって、2つのテーブルの関係は、`users : messages = 1 : 0~多`
  
 #### 例２:usersテーブルとaddressテーブル(会員登録ページで必須項目を埋める時のイメージ)
- 前提：会員登録時、ユーザーは請求先と配送先を2つ登録しないといけない。2つとも同じ住所の場合は、1レコードになる。(画像のは異なる場合のレコード)
- userのデータも、addressのデータも、登録時に保存される
- user
  - 1人のuserは必ず1つ以上の住所のデータを持つ
  - 請求先と配送先の住所が異なる場合は、レコードが2つ登録されるので、2つの時もある。
- address
  - 1つの住所は、必ず1人のユーザーに紐づいている。
  - 0人の場合も、複数人の場合もあり得ない
- よって、2つのテーブルの関係は、`users : addresses = 1 : 1..2`

### Railsはリレーションシップを3種類でしか区別しない
Railsの世界では、リレーションシップは以下の3種類しか無い。
- 1 : 1 
- 1 : 多
- 多 : 多  

Railsには、`1 : 1..2`や、`1 : 0~多`など細かいリレーションシップを区別する機能はないので、**開発者自身がDBを作る前に、リレーションシップを詳細に考える必要がある。**

**Comment by Saki-htr** [comment]
# DB設計の提出物
お疲れ様です。
自作サービスのDB設計を作成しましたので、ご確認をお願いいたします。

## ER図
![image](https://user-images.githubusercontent.com/58052292/179943159-0b42b679-eb3b-4949-81c0-4a36628053f9.png)

## 実際のデータを入れてみた時のDB

![image](https://user-images.githubusercontent.com/58052292/179944183-03035258-644a-441a-8186-bd27927a8cb1.png)


## 各テーブル同士のリレーションシップ(詳細)
### users と assigned_issues の関係
- 【結論】`users : assigned_issues =  1〜10 : 0〜*`(多対多)

#### 根拠
- user から見た assigned_issues 
  - 私のアプリに登録した時点で、まだissueを割り振られていない場合があるため、0件が有り得る
  - チーム開発の運用ルールでは、「割り振られたissueが、合計20ptを超えるとチーム開発のプラクティス卒業」なので、1~複数件も有り得る。
  - 想定される最高数は、誰が何個振られるか読めない&チーム開発を卒業後に就職前にまた戻ってきてチーム開発をやるケースもあり、定まらないため、`*`とする。
- assigned_issuesから見たuser
  - assigned_issuesテーブルには、"issueのassignee に誰かしら登録されている状態の"issueのデータのみを保存することになるため、0件はあり得ない。なので、最低1人以上のuserとは紐づいている
  - チーム開発の現行のルールでは、issueを割り振られる際は、issueのassigneeに受講生が1人登録され、デザインが必要な場合はmachidaさんをassigneeに登録することになっている。受講生が2人以上assigneeに登録される可能性は低いので、運用ルールを基に考えるとassigneeに登録されるのは最高2名。
  - しかしGitHubの仕様では、assigneeは1つのissueに**10人まで**登録できる。チーム開発の運用ルールとGitHubの仕様、どちらを基準に設計するか迷ったが、ルールは変更されるかもしれないため、GitHubの仕様を基準に考えることにした。よって、`1~10`
    - [GitHub の他のユーザに Issue およびPull Requestをアサインする \- GitHub Docs](https://docs.github.com/ja/issues/tracking-your-work-with-issues/assigning-issues-and-pull-requests-to-other-github-users)より
     > パブリックリポジトリのIssue及びPull Request、そして有料アカウントのプライベートリポジトリでは、**最大10人**を割り当てできます。

### users と review_requested_pull_requests の関係
- 【結論】`users : review_requested_pull_requests =  1〜15 : 0〜*`(多対多)
#### 根拠
- userから見たreview_requested_pull_request
  - レビューを依頼を1件も受けていない可能性がある
  - 同時に、1件〜複数件依頼される可能性もある
  - GitHubの仕様上、同時にReviewerに登録されるPRの数には上限がないので、`*`とする
  - よって、`0〜*`
- review_requested_pull_requestから見たuser
  - review_requested_pull_requestテーブルには、"PRのreviewer に誰かしら登録されている状態"のPRのデータのみを保存することになるため、0件はあり得ない。なので、最低1人以上のuserとは紐づいている
  - チーム開発の現行のルールでは、受講生1人&komagataさんの合計2名がレビュワーとして登録されることになっている。基本的に、最初に受講生１名に依頼し(Reviewerに登録し)、そのApprove後、komagataさんをReviewerに登録してレビュー依頼するので、Approve待ちのReviewerが同時に複数名存在するケースはほぼ無い。
  - しかし、GitHubの仕様上、bootcampリポジトリでは、Reviewerを最大15名まで1つのPRに登録することができる。
  - よって、GitHubの仕様を基準に考え、`1~15`
  
<img width="299" alt="image" src="https://user-images.githubusercontent.com/58052292/179972750-e72011f3-e489-4f95-9b88-bbd798ea53ba.png">

  
  
## 実際にRailsでテーブルを作成する際のマイグレーションファイル

- [ ] 中間テーブルのマイグレーションファイルと、関連付けのオプション(through,dependent)を考える

**Comment by kfukai23** [comment]
検討の過程がしっかり残っていてよいですね:+1: また、やりたいことはしっかり実現できそうに思いました。
以下、どこかに書かれていることをお聞きしているかもしれませんがお答えいただきたいです〜（エレベーターピッチやペーパープロトタイピングには目を通していますが、この設計にたどり着くまでに検討された過程が記されている issue などまでじっくり読むのはさすがにちょっと難しいので...mm）

- ユーザからのアクセスがあったら都度 API リクエストするのではなく、定期的にリクエストして結果を DB に持つようにした理由が知りたいです〜
  - 定期的にリクエストする方法だと（スパンにもよりますが）リアルタイム性は損なわれる点が気になりました。そのデメリットと、どんなメリットを天秤にかけたのか知りたいです
  - ペーパープロトタイピングの話になってしまいますが、定期的にリクエストする方法でいくなら、データの最終取得日はどこかに表示されていると親切そうに思いました
- RAW_*** を永続化しておく理由を教えてください:pray: API レスポンスから必要なデータを抽出して DB に入れた後は必要ないのでは？と思ったからです
  - RAW_*** を Issue や PR そのもののレコードと別に持っておく理由も気になりました
- ASSIGNED_ISSUES は user_id の有無が ER 図と実際のデータ例とで食い違っていますがどちらが正ですか？（多分後者かな、とは思いますが:eyes:）
- PR の URL はまるまる保存せず、すべての URL で共通なものは省いて保存しても良さそうです
  - ドメイン名や organization 名、リポジトリ名など。これらは定数かなにかでアプリ内に持っておいて、PR の ID と都度組み合わせて URL を組み立て表示するイメージです
  - 可能性は高くないですが、ドメイン名や URL の構造が変更になっても定数を変えるだけで引き続きアクセスできるかなと
    - もし文字列で持っていると、（GitHub 側が旧 URL を新 URL にリダイレクトしてくれるのでないなら）レコード全部更新するはめになります
  - というか、その路線でいくなら PR の id だけあればよいかも？ID だけにするならカラム減らせてシンプルになるし、データ量の節約にもなりますね

**Comment by Saki-htr** [comment]
お待たせしてすみません🙏 大変丁寧にレビューしてくださり、ありがとうございます!
ER図と実際のデータ例を修正し、提出2回目として記載しました。ご確認をお願いいたします。

## ユーザからのアクセスがあったら都度 API リクエストするのではなく、定期的にリクエストして結果を DB に持つようにした理由
- 理由は、OAuthアプリケーションからGitHubの REST APIへのリクエストは、1時間に5,000回までの制限があるためです。ユーザーが私の自作アプリでリロードする(私の自作アプリにリクエストを送る)度に、GitHubAPIにリクエストを送るように設定してしまうと、1時間に5000回という制限を超えてしまう恐れがあるためです。リリース後、私の自作アプリにレート制限を超えるリクエストが来る可能性は低いかもしれませんが、起こり得るリスクに対処しておいた方が良いと考えました。
    - [REST API のリソース \- GitHub Docs](https://docs.github.com/ja/rest/overview/resources-in-the-rest-api#rate-limiting)より
    > ユーザーからサーバーへのリクエストは、認証されたユーザーごとに1時間あたり5,000リクエストに制限されています。ユーザーまたは**ユーザーが所有する個人アクセストークンによって承認されたOAuthアプリケーションからのすべてのリクエスト、およびユーザーの認証資格情報のいずれかで認証されたリクエストは、そのユーザーに対して1時間あたり5,000リクエスト**という同じクォータを共有します。
- 解決策として、ユーザー→自作サービスへのリクエスト と、 自作サービス→GitHubAPIへのリクエストの処理を分けることにし、GitHubAPIへのリクエストは、定期的に送ることにしました。


## リクエストのスパンも知りたいです
- 1分間に1回を考えています。
- 理由は以下の2点です。
    - 1分間に1回であれば、ユーザーが自作アプリにリクエストを送った時に表示される情報のリアルタイム度を高く保てると考えたため。
    - 1hに5000回のレート制限を超えないため。

## 定期的にリクエストする方法でいくなら、データの最終取得日はどこかに表示されていると親切そうに思いました

たしかにその方がユーザーから見て、「今見ているのが、いつの時点の情報か」見えて親切ですね!仰る通りにしようと思います。
早速issueを立てました。
[データの最終取得日を表示する · Issue \#63 · Saki\-htr/fjord\-choice](https://github.com/Saki-htr/fjord-choice/issues/63)

## RAW_*** を永続化しておく理由

理由について、以下のissueにまとめましたので、お手数をおかけして申し訳ありませんが、ご確認いただけますと幸いです🙏
[APIから取得した生のJSONデータをアプリ側に保存するかどうか決める · Issue \#43 · Saki\-htr/fjord\-choice](https://github.com/Saki-htr/fjord-choice/issues/43)

## RAW_*** を Issue や PR そのもののレコードと別のテーブルに持っておく理由

すみません🙏 こちら特に意図せず別テーブルにしていました。
改めて別テーブルにすべきか考えたところ、ユーザーが「メンバーから外れる」ボタンをクリックした時のDBのレコードの扱いを、生データ(RAW_*** テーブル)と表形式のデータ(Issue や PR そのもののレコード)で分けたいと思ったため、別テーブルにした方が良いのではないかと考えました。

具体的にレコードをどのようにするかはまだ決められていないのですが、
- 生データは永久に保存
- Issue や PR そのもののレコードは、一度メンバー登録し、外れた人が、再び登録する可能性があるため、「メンバーから外れる」ボタンクリック後すぐには削除せず、1~2年経ったら削除

を考えています。


## ASSIGNED_ISSUES は user_id の有無が ER 図と実際のデータ例とで食い違っていますがどちらが正ですか？（多分後者かな、とは思いますが👀）

申し訳ありません🙇‍♀️ 実際のデータ例の方が合っていますので、ER図の`assigned_issues`と`review_requested_pull_requests`から`user_id`を削除しました。

## PR の URL はまるまる保存せず、すべての URL で共通なものは省いて保存しても良さそうです

ドメイン名やURLの構造が変更になる可能性は考慮できていませんでした…!
変更になった時のレコード更新が大変なため、仰る通り、PRのIDのみ保存しようと思います。
PRのIDは、以下のように取得した生データの `number` というキーに入っていたので、カラム名は `url` ではなく `number` に変更しようと思います。

```json
[
  {
    "url": "https://api.github.com/repos/fjordllc/bootcamp/pulls/5243",
    "id": 1001992155,
    "node_id": "PR_kwDOAE5q5847uS_b",
    "html_url": "https://github.com/fjordllc/bootcamp/pull/5243",
    "diff_url": "https://github.com/fjordllc/bootcamp/pull/5243.diff",
    "patch_url": "https://github.com/fjordllc/bootcamp/pull/5243.patch",
    "issue_url": "https://api.github.com/repos/fjordllc/bootcamp/issues/5243",
    "number": 5243, #こちらです
    "state": "open",
    "locked": false,
    "title": "アイコン付きメンション時のアイコンをリサイズしました",
    "user": {

    (...省略)
```
ER図と実際のデータの例も変更しました🙏


## 懸念点：中間テーブルの適切な名前の付け方

2つの中間テーブルの適切な名前の付け方が分かりません🙏

`users`と`assigned_issues` という2つのテーブルの中間テーブルを作る時、 Railsで `users ＿ assigned_issues`という名前のテーブルは作成可能でしょうか?

3つの単語の分かれ目が、テーブルの分かれ目なのか、1つのテーブルの中の単語の分かれ目なのか、Railsは判断できるのでしょうか?bootcampリポジトリやQiita記事を見たところ、中間テーブルは必ず`users_book`というように1単語同士で作っていたので、判断できないのではないかと懸念しています。

もし不可能な場合、どのような名前を付けるのが適切かご指摘いただけますと幸いです🙇‍♀️

よろしくお願いいたします。

**Comment by kfukai23** [comment]
## ユーザからのアクセスがあったら都度 API リクエストするのではなく、定期的にリクエストして結果を DB に持つようにした理由
> リリース後、私の自作アプリにレート制限を超えるリクエストが来る可能性は低いかもしれませんが、起こり得るリスクに対処しておいた方が良いと考えました。
なるほどです:thinking: ちなみに、このサービスへのリクエストは、1時間あたり最大どのくらい来る想定なのでしょう？
1時間につきアクセスするユーザーが500人いて、1人あたり10回（6分に一回）アクセスすると5,000回に到達する計算です。これは本当に起こりうるのでしょうか？

確かに起こりうるリスクに対応しておくのも大事なんですが、一方でソフトウェア開発には [YAGNI](https://ja.wikipedia.org/wiki/YAGNI) という原則があります。
リスクに備えるコストはタダではないですよね。そのコストを払うにはちょっと根拠が弱い（ように見える）のが気になりました。

ただ、別の観点から、結果を DB に持つという決定自体は良いと思います。ユーザーからのリクエストがあってから API を叩き、色々と計算や処理をしてレスポンスを返すやり方だと、API からのレスポンスが遅い時の処理など、それはそれで考えることが少し増えるかなーと思うからです。
今回の要件を考えると1分ごとの更新で求められるリアルタイム性は十分満たせるでしょうし、それならユーザーからのリクエストにすぐ smooth_choice から応答できる（GitHub API をリアルタイムで用いなくても完結する）メリットはそれなりに大きそうに思いました。
世にはユーザからのリクエストをきっかけに API を叩いて結果を返すようなアプリも普通にあるので、その難しさに向き合ってみるのもいい勉強だとは思うんですが、DB に持って予め準備しておくやり方のほうがたぶん作りやすいと思います。

## RAW_*** を Issue や PR そのもののレコードと別のテーブルに持っておく理由

> 改めて別テーブルにすべきか考えたところ、ユーザーが「メンバーから外れる」ボタンをクリックした時のDBのレコードの扱いを、生データ(RAW_*** テーブル)と表形式のデータ(Issue や PR そのもののレコード)で分けたいと思ったため、別テーブルにした方が良いのではないかと考えました。

なるほどー確かにアプリで扱いたい「実際の Issue や PR」と「控えとしての JSON レスポンスデータ」は性質が違いますもんね。理解しました！良いと思います〜


## 懸念点：中間テーブルの適切な名前の付け方

> 3つの単語の分かれ目が、テーブルの分かれ目なのか、1つのテーブルの中の単語の分かれ目なのか、Railsは判断できるのでしょうか?bootcampリポジトリやQiita記事を見たところ、中間テーブルは必ずusers_bookというように1単語同士で作っていたので、判断できないのではないかと懸念しています。

これはですね、まっさらな Rails アプリを new して、自分で試してみるのが一番です！！
あと根本的には「Rails が中間テーブル名をどのように認識しているか」という話なので、そこも調べてみましょう。

**Comment by kfukai23** [comment]
（追加で質問を投げたり、中間テーブルの件は Saki さんの中ではまだ解決してないものの、DB 設計自体は OK と思いますので、課題としては合格とさせていただきます〜）

**Comment by Saki-htr** [comment]
かいとさん、ありがとうございました🙏✨
合格をいただきましたので、closeいたします。

**Comment by Saki-htr** [comment]
## 提出物との変更点
- 中間テーブル`user_review_requested_pull_requests`が長すぎて`db:migrate`できなかった→`user_pull_requests`テーブルに変更
- JSON生データを入れる2つのテーブル名とカラム名が同じでややこしいので、カラム名を`issue`,`pull_request`に変更
- Userテーブルの`avatar_url`は、URL丸ごと入れるつもりだったが、これもPRのnumberと同様、URLを見てみたら、GitHubのURLにそのユーザーのGitHubでの番号を入れているだけだったので、カラム名を`github_id`に変更して、GitHubのidだけ取得してURLを生成することにした。

**Comment by Saki-htr** [comment]
### 提出物との変更点
- RawIssueテーブルにissueの番号(`/issues/1`の1の部分)を保存するカラムを作成した

**Comment by Saki-htr** [comment]
![image](https://user-images.githubusercontent.com/58052292/183830551-a471ed40-4648-490d-94d4-cc1d1d935563.png)

**Comment by Saki-htr** [comment]
- #85 

- `users`カラムを追加
<img width="904" alt="image" src="https://user-images.githubusercontent.com/58052292/184518289-725ae4e5-d8ee-4f57-805b-a9497267ab8c.png">


- 参考：[8/11\(水\) 梅本さんペアプロ メモ \- HackMD](https://hackmd.io/Y62a5EWQTUeDulfvk2IuNA?view)
